[package]
name = "aes67-streamer"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/wiccy46/aes67-streamer"
description = "Audio File Streamer on RTP with AES67 compliance"

[dependencies]
config = { path = "../config" }
audio = { path = "../audio" }
env_logger = "0.11.6"
log = "0.4.26"
