[package]
name = "streamer-core"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/wiccy46/aes67-tools"
description = "Reusable AES67 streaming engine for aes67-streamer"

[dependencies]
audio = { path = "../audio" }
network = { path = "../network" }
ptp = { path = "../ptp" }
anyhow = "1.0"
log = "0.4.26"
rand = "0.8.5"
tokio = { version = "1.0", features = ["full"] }
tokio-util = "0.7"

[dev-dependencies]
hound = "3.5"
